- type: job
  id: Enginseer
  name: job-name-enginseer
  description: job-description-enginseer
  playTimeTracker: JobEnginseer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Mechanicus
      min: 14400 #4 hrs
  startingGear: StationEngineerGear
  icon: "JobIconEnginseer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics
