- type: job
  id: Explorator
  name: job-name-explorator
  description: job-description-explorator
  playTimeTracker: JobExplorator
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Mechanicus
      min: 21600 # 6 hrs
  icon: "JobIconExplorator"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
