- type: job
  id: ChaplainWH40K
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplainWH40K
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Personnel
      min: 14400 # 4 hours
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Shadowkin
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - ShadowkinBlackeye
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-rd
  access:
  - Chapel
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser
    - type: Psionic
      powerRollMultiplier: 3
    - type: InnatePsionicPowers
      powersToAdd:
        - TelepathyPower
        - HealingWordPower
        - SummonRemiliaPower
