- type: job
  id: ChemistWH40K
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemistWH40K
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Personnel
      min: 28800 # DeltaV - 8 hours
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 1.75
